#!/usr/bin/env bash
#
# author-frozen-corpus.sh — author (or extend) the FROZEN benchmark-corpus
# manifest from PINNED git sources.
#
# For each source it shallow-fetches the exact pinned commit, selects files,
# computes the sha256 of each from the local checkout, and appends a manifest
# entry whose `url` is the commit-pinned raw.githubusercontent path (which
# returns byte-identical content, so the recorded sha256 is what
# build-corpus.sh --frozen will later verify). Also emits a NOTICE attribution
# file. 8 shallow fetches instead of ~800 raw HTTP fetches.
#
# Usage:  author-frozen-corpus.sh <workdir> <out_manifest> <out_notice>
#
# Output manifest conforms to scripts/bench/corpus-manifest.schema.md (frozen).
# This run authors the CODE + MD (prose) tiers; CSV/PDF/Gutenberg are appended
# by later runs.
set -uo pipefail

WORK="${1:-/tmp/frozen-author}"
OUT_MANIFEST="${2:-/tmp/frozen-corpus-manifest.wip.yaml}"
OUT_NOTICE="${3:-/tmp/frozen-corpus-NOTICE.txt}"

mkdir -p "$WORK"
: > "$OUT_MANIFEST"
: > "$OUT_NOTICE"
TOTAL=0

log() { echo "[author] $*" >&2; }

{
  echo "version: 1"
  echo "mode: frozen"
  echo "corpus_id: bench-v1"
  echo "# WIP: authored tiers = code, md. Pending: csv, pdf, gutenberg."
  echo "entries:"
} >> "$OUT_MANIFEST"

{
  echo "FolderMCP benchmark corpus (bench-v1) — source attribution / NOTICE"
  echo "Generated by scripts/bench/author-frozen-corpus.sh. The corpus is NOT"
  echo "redistributed here; build-corpus.sh --frozen re-fetches each file from"
  echo "its pinned upstream URL. Attribution for CC-BY sources is recorded below."
  echo
} >> "$OUT_NOTICE"

note() { printf '  %-22s %-18s %s\n' "$1" "$2" "$3" >> "$OUT_NOTICE"; }

# clone_repo OWNER REPO SHA -> prints checkout dir on stdout (empty on failure)
clone_repo() {
  local owner="$1" repo="$2" sha="$3"
  local dir="$WORK/$repo"
  if [ ! -d "$dir/.git" ]; then
    rm -rf "$dir"; mkdir -p "$dir"
    if ! ( cd "$dir" \
            && git init -q \
            && git remote add origin "https://github.com/$owner/$repo.git" \
            && git fetch -q --depth 1 origin "$sha" \
            && git checkout -q FETCH_HEAD ) >&2; then
      log "FATAL clone $owner/$repo@$sha"
      rm -rf "$dir"
      return 1
    fi
  fi
  echo "$dir"
}

# emit_entries_file DIR OWNER REPO SHA LICENSE STRATUM LISTFILE -> prints count
# Reads relpaths from a FILE (not a pipe) so it runs in the current shell.
emit_entries_file() {
  local dir="$1" owner="$2" repo="$3" sha="$4" license="$5" stratum="$6" listfile="$7"
  local rel sum dest id n=0
  while IFS= read -r rel; do
    [ -n "$rel" ] || continue
    [ -f "$dir/$rel" ] || continue
    sum="$(sha256sum "$dir/$rel" | awk '{print $1}')"
    dest="$stratum/$repo/$rel"
    id="$stratum-$repo-$(printf '%s' "$rel" | tr '/.' '--' | tr -cd 'A-Za-z0-9_-')"
    {
      printf '  - id: %s\n' "$id"
      printf '    url: https://raw.githubusercontent.com/%s/%s/%s/%s\n' "$owner" "$repo" "$sha" "$rel"
      printf '    sha256: %s\n' "$sum"
      printf '    license: %s\n' "$license"
      printf '    stratum: %s\n' "$stratum"
      printf '    dest: %s\n' "$dest"
      printf '    source: %s/%s@%s\n' "$owner" "$repo" "${sha:0:12}"
    } >> "$OUT_MANIFEST"
    n=$((n + 1))
  done < "$listfile"
  echo "$n"
}

# run_source DIR OWNER REPO SHA LICENSE STRATUM MAX LISTFILE
run_source() {
  local dir="$1" owner="$2" repo="$3" sha="$4" license="$5" stratum="$6" max="$7" listfile="$8"
  local sel="$listfile.sel" n
  if [ "$max" -gt 0 ]; then
    LC_ALL=C sort "$listfile" | head -n "$max" > "$sel"
  else
    LC_ALL=C sort "$listfile" > "$sel"
  fi
  n="$(emit_entries_file "$dir" "$owner" "$repo" "$sha" "$license" "$stratum" "$sel")"
  TOTAL=$((TOTAL + n))
  log "$stratum/$repo: $n files"
  note "$owner/$repo" "$license" "$stratum ($n files) https://github.com/$owner/$repo/tree/$sha"
}

LIST="$WORK/list.txt"

# ───────────────────────── CODE tier ─────────────────────────
S_GIN=34dac209ffb6ef85cc78c5d217bbb7ad001d68fd
S_COBRA=ad460ea8f249db69c943a365fb84f3a59042d54e
S_FLASK=36e4a824f340fdee7ed50937ba8e7f6bc7d17f81
S_REQ=23953c0c875219a715f081cf3de7c149a7629ccf
S_RG=dfe4a81d2591daca76d25ae4e052c34b26578155
S_VUE=c0606e91798c8dca4f33d101e1dd836d672592c1

dir="$(clone_repo gin-gonic gin "$S_GIN")"
[ -n "$dir" ] && { ( cd "$dir" && find . -name '*.go' ! -name '*.pb.go' -type f ) | sed 's|^\./||' > "$LIST"; run_source "$dir" gin-gonic gin "$S_GIN" MIT code 0 "$LIST"; }

dir="$(clone_repo spf13 cobra "$S_COBRA")"
[ -n "$dir" ] && { ( cd "$dir" && find . -name '*.go' ! -name '*.pb.go' -type f ) | sed 's|^\./||' > "$LIST"; run_source "$dir" spf13 cobra "$S_COBRA" Apache-2.0 code 0 "$LIST"; }

dir="$(clone_repo pallets flask "$S_FLASK")"
[ -n "$dir" ] && { ( cd "$dir" && find . -name '*.py' -type f ) | sed 's|^\./||' > "$LIST"; run_source "$dir" pallets flask "$S_FLASK" BSD-3-Clause code 0 "$LIST"; }

dir="$(clone_repo psf requests "$S_REQ")"
[ -n "$dir" ] && { ( cd "$dir" && find . -name '*.py' -type f ) | sed 's|^\./||' > "$LIST"; run_source "$dir" psf requests "$S_REQ" Apache-2.0 code 0 "$LIST"; }

dir="$(clone_repo BurntSushi ripgrep "$S_RG")"
[ -n "$dir" ] && { ( cd "$dir" && find . -name '*.rs' -type f ) | sed 's|^\./||' > "$LIST"; run_source "$dir" BurntSushi ripgrep "$S_RG" MIT code 0 "$LIST"; }

dir="$(clone_repo vuejs core "$S_VUE")"
[ -n "$dir" ] && { ( cd "$dir" && find packages -path '*/src/*' -name '*.ts' ! -name '*.d.ts' ! -path '*/__tests__/*' ! -name '*.spec.ts' -type f ) | sed 's|^\./||' > "$LIST"; run_source "$dir" vuejs core "$S_VUE" MIT code 200 "$LIST"; }

# ───────────────────────── MD (prose) tier ─────────────────────────
S_BOOK=8cc0cb138998ee0502504ca1247b51de9161197c
S_K8S=d41a4597a8bc5e3983a35f85eb62765037da796b

dir="$(clone_repo rust-lang book "$S_BOOK")"
[ -n "$dir" ] && { ( cd "$dir" && find src -maxdepth 1 -name '*.md' ! -name 'SUMMARY.md' -type f ) | sed 's|^\./||' > "$LIST"; run_source "$dir" rust-lang book "$S_BOOK" MIT-OR-Apache-2.0 md 0 "$LIST"; }

dir="$(clone_repo kubernetes website "$S_K8S")"
[ -n "$dir" ] && { ( cd "$dir" && find content/en/docs/concepts content/en/docs/tasks content/en/docs/tutorials -name '*.md' -type f 2>/dev/null ) | sed 's|^\./||' > "$LIST"; run_source "$dir" kubernetes website "$S_K8S" CC-BY-4.0 md 150 "$LIST"; }

log "TOTAL entries authored: $TOTAL"
echo "## TOTAL: $TOTAL entries" >> "$OUT_NOTICE"

# ───────────────────────── sample round-trip validation ─────────────────────────
log "validating sample raw URLs round-trip (5 entries)..."
paste -d'|' \
  <(grep -E '^[[:space:]]+url: ' "$OUT_MANIFEST" | sed 's/.*url: //') \
  <(grep -E '^[[:space:]]+sha256: ' "$OUT_MANIFEST" | sed 's/.*sha256: //') \
  | awk 'NR%150==1' | head -5 | while IFS='|' read -r u s; do
    g="$(curl -fsSL --retry 2 "$u" | sha256sum | awk '{print $1}')"
    if [ "$g" = "$s" ]; then echo "[author] OK  $u" >&2; else echo "[author] MISMATCH $u want=$s got=$g" >&2; fi
  done

log "DONE. manifest=$OUT_MANIFEST notice=$OUT_NOTICE"
